import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#f4f7fb",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e4e8ef",
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#172033",
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#5f6b7a",
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e4e8ef",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#eef2f7",
    alignItems: "center",
  },
  tabButtonActive: {
    backgroundColor: "#2f6fed",
  },
  tabText: {
    color: "#415066",
    fontWeight: "600",
  },
  tabTextActive: {
    color: "#ffffff",
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 32,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#172033",
    marginBottom: 8,
  },
  sectionBody: {
    fontSize: 14,
    color: "#5f6b7a",
    marginBottom: 16,
    lineHeight: 20,
  },
  subsectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#172033",
    marginTop: 8,
    marginBottom: 10,
  },
  summaryCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#e4e8ef",
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#172033",
    marginBottom: 8,
  },
  summaryStat: {
    fontSize: 15,
    color: "#3e4b5c",
    marginBottom: 6,
  },
  summaryHighlight: {
    marginTop: 10,
    fontSize: 14,
    color: "#1c4fb6",
    fontWeight: "600",
    lineHeight: 20,
  },
  progressWrapper: {
    marginTop: 10,
    marginBottom: 6,
  },
  progressBackground: {
    height: 12,
    borderRadius: 999,
    backgroundColor: "#e6ecf5",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#2f6fed",
    borderRadius: 999,
  },
  progressText: {
    marginTop: 6,
    color: "#4d5c70",
    fontSize: 13,
    fontWeight: "600",
  },
  checklistRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e4e8ef",
  },
  checklistRowChecked: {
    backgroundColor: "#eef6ef",
    borderColor: "#bcd8bf",
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: "#9ca7b5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: "#2c9c5f",
    borderColor: "#2c9c5f",
  },
  checkboxMark: {
    color: "#ffffff",
    fontWeight: "700",
  },
  checklistTextBlock: {
    flex: 1,
  },
  checklistLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#172033",
    marginBottom: 4,
  },
  checklistReason: {
    fontSize: 13,
    color: "#617184",
    lineHeight: 18,
  },
  checklistPoints: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2f6fed",
    marginLeft: 8,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e4e8ef",
  },
  sectionCard: {
    shadowColor: "#10213a",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sectionCardSubtitle: {
    marginBottom: 10,
    color: "#64748a",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#172033",
    marginBottom: 6,
  },
  cardBody: {
    fontSize: 14,
    color: "#4e5c70",
    lineHeight: 20,
    marginBottom: 4,
  },
  alertRow: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#edf1f6",
  },
  alertTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#172033",
    marginBottom: 4,
  },
  metricGrid: {
    marginTop: 8,
    gap: 10,
  },
  metricCard: {
    backgroundColor: "#f8fbff",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#dbe7ff",
  },
  metricLabel: {
    fontSize: 12,
    color: "#64748a",
    marginBottom: 4,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  metricValue: {
    fontSize: 18,
    color: "#172033",
    fontWeight: "700",
  },
  searchInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d9e1ec",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    marginBottom: 14,
  },
  primaryButton: {
    marginTop: 12,
    backgroundColor: "#2f6fed",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  secondaryButton: {
    marginTop: 12,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#edf2fb",
  },
  secondaryButtonText: {
    color: "#2f6fed",
    fontSize: 14,
    fontWeight: "700",
  },
  errorText: {
    color: "#b43333",
    fontSize: 14,
    lineHeight: 20,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(10, 18, 30, 0.45)",
    justifyContent: "center",
    padding: 18,
  },
  modalCard: {
    maxHeight: "80%",
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
  },
  smallModalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  modalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: "#172033",
    marginRight: 12,
  },
  modalClose: {
    color: "#2f6fed",
    fontWeight: "700",
  },
  modalSubheading: {
    fontSize: 13,
    color: "#64748a",
    marginBottom: 14,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  stepNumber: {
    width: 24,
    fontSize: 14,
    fontWeight: "700",
    color: "#2f6fed",
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    color: "#415066",
    lineHeight: 20,
  },

  welcomeWrap: {
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  welcomeCard: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 24,
  },
  welcomeTitle: {
    fontSize: 30,
    fontWeight: "800",
    color: "#172033",
    marginBottom: 12,
  },
  welcomeBody: {
    fontSize: 16,
    color: "#4e5c70",
    lineHeight: 24,
    marginBottom: 20,
  },
  screenPad: {
    flex: 1,
    backgroundColor: "#f4f7fb",
    padding: 24,
    justifyContent: "center",
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 99,
    backgroundColor: "#d4dbe7",
  },
  dotActive: {
    backgroundColor: "#2f6fed",
  },
  emergencyWrap: {
    flex: 1,
    backgroundColor: "#fff5f5",
  },
  emergencyTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#8f1010",
    marginBottom: 8,
  },
  emergencyText: {
    fontSize: 15,
    color: "#6d2a2a",
    marginBottom: 16,
    lineHeight: 22,
  },
  emergencyCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#f0caca",
  },
  dangerButton: {
    backgroundColor: "#c62828",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  dangerButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
  riskBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 10,
  },
  riskLow: {
    backgroundColor: "#dff4e7",
  },
  riskModerate: {
    backgroundColor: "#fff1cc",
  },
  riskHigh: {
    backgroundColor: "#ffd6d6",
  },
  riskBadgeText: {
    fontWeight: "700",
    color: "#243447",
  },
  screenScroll: {
  flex: 1,
  backgroundColor: "#f4f7fb",
},
screenScrollContent: {
  padding: 16,
  paddingBottom: 40,
  flexGrow: 1,
},
mapScreenWrap: {
  flex: 1,
  backgroundColor: "#f4f7fb",
},
map: {
  flex: 1,
  minHeight: 420,
},
mapInfoCard: {
  backgroundColor: "#ffffff",
  padding: 16,
  borderTopLeftRadius: 18,
  borderTopRightRadius: 18,
  borderWidth: 1,
  borderColor: "#e4e8ef",
},
chatMessages: {
  flex: 1,
  marginBottom: 12,
},
chatMessagesContent: {
  paddingBottom: 12,
  gap: 10,
},
chatBubble: {
  maxWidth: "82%",
  padding: 12,
  borderRadius: 14,
},
chatBubbleBot: {
  alignSelf: "flex-start",
  backgroundColor: "#eef2f7",
},
chatBubbleUser: {
  alignSelf: "flex-end",
  backgroundColor: "#2f6fed",
},
chatBubbleText: {
  fontSize: 14,
  lineHeight: 20,
},
chatBubbleTextBot: {
  color: "#172033",
},
chatBubbleTextUser: {
  color: "#ffffff",
},
chatInputRow: {
  gap: 10,
},
chatInput: {
  backgroundColor: "#ffffff",
  borderWidth: 1,
  borderColor: "#d9e1ec",
  borderRadius: 12,
  paddingHorizontal: 14,
  paddingVertical: 12,
  fontSize: 14,
  minHeight: 50,
},
quickQuestionsWrap: {
  flexDirection: "row",
  flexWrap: "wrap",
  gap: 8,
  marginBottom: 12,
},

quickQuestionBtn: {
  backgroundColor: "#eef2f7",
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 20,
  borderWidth: 1,
  borderColor: "#d9e1ec",
},

quickQuestionText: {
  fontSize: 12,
  color: "#2f6fed",
},
});